use std::fmt;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TokenType {
    LET, VAR, FN, IF, ELIF, ELSE, FOR, WHILE, IN, RETURN, GO, AWAIT, TRY, HANDLE, PANIC, DEFER, MATCH, AS,
    ANNOT_MANUAL, ANNOT_RC, ANNOT_SYSTEM_THREAD, ANNOT_EVENT_LOOP, ANNOT_INLINE_ASM, ANNOT_RUST, ANNOT_GO_LANG, ANNOT_C, ANNOT_JAVA, ANNOT_PYTHON, ANNOT_JAVASCRIPT, ANNOT_WEB, ANNOT_MOBILE, ANNOT_CLI, ANNOT_DESKTOP, ANNOT_MODULE,
    PLUS, MINUS, STAR, SLASH, PERCENT, ASSIGN, EQ, NE, LT, GT, LE, GE, ANDAND, OROR, NOT, QMARK, COLON, SEMI, LPAREN, RPAREN, LBRACKET, RBRACKET, LBRACE, RBRACE, COMMA, DOT,
    INTEGER, FLOAT, STRING, BOOLEAN, NULL, IDENTIFIER, NEWLINE, INDENT, DEDENT, EOF,
}

#[derive(Debug, Clone)]
pub struct Token {
    pub ty: TokenType,
    pub value: String,
    pub line: usize,
    pub column: usize,
}